spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://100.100.30.153:23306/artvu
    username: appartvu
    password: Ra$5Je23

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true


  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  open-api:
    secretKey: "9bc5a206710943769d657e163212035d"

logging:
  file:
    name: service.log
  logback:
    rolling policy:
      file-name-pattern: service.%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
  pattern:
    dateformat: Asia/Seoul
